### ISSUE TITLE
大佬能否出个教程啊

### ISSUE THREAD

**Issue by mengxiangke** [TkzcM/baiduwp#1]
部署了不管用的
Usage
headers:{
    'user-agent': 'Some UA',
    'Cookie': 'BDUSS=INPUT YOUR BDUSS HERE; STOKEN=INPUT YOUR STOKEN HERE'
  }
这儿看不懂

**Comment by TkzcM** [comment]
在所有headers里填入你自己的BDUSS和STOKEN
