### ISSUE TITLE
最新版本获取下载链接失败

### ISSUE THREAD

**Issue by cloudtom** [TkzcM/baiduwp#14]
提示：获取下载链接失败
未知错误

目测猜测是在getRealLink的步骤中发生错误
位于文件的747行
该方法用fetch访问由上一步getDlink方法获得的dlink

该方法访问的百度链接是：
https://d.pcs.baidu.com/file/29f4f024d8e0056e72a8adb6e541f787?fid=1473016660-250528-1033140170268273&dstime=1597750317&rt=sh&sign=FDtAERV-DCb740ccc5511e5e8fedcff06b081203-WLHnZb7oK%2FvXH6I6BwrnXU0D2%2BM%3D&expires=1h&chkv=1&chkbd=0&chkpc=&dp-logid=8812956136143474880&dp-callid=0&shareid=773538056&r=729913511
访问上面链接百度返回的数据：
{error_code: 31360, error_msg: "expire time out error", request_id: 8812956136143475000}

猜测是由于百度服务器返回的dlink的dstime参数有误，时间慢了1小时，如修改dlink里的dstime为当前unix时间戳后则提示：{"error_code":31362,"error_msg":"sign error","request_id":8812956136143474880}

**Comment by TkzcM** [comment]
你的 clienttype 不是 12

**Comment by cloudtom** [comment]
> 你的 clienttype 不是 12

请问clienttype在哪里修改？我是直接复制仓库里最新的index.js代码只改了stoken，BDUSS和SVIPBDUSS没有改其他的

**Comment by TkzcM** [comment]
在 BDUSS 和 SVIPBDUSS 正确，且 clienttype 为 12 的情况下，获取到的链接 expires=8h
所以检查你的cookie吧

**Comment by cloudtom** [comment]
> 在 BDUSS 和 SVIPBDUSS 正确，且 clienttype 为 12 的情况下，获取到的链接 expires=8h
> 所以检查你的cookie吧

请问一下 BDUSS 和 SVIPBDUSS 有什么区别吗，能不能填写同一个百度账号（该账号已经是会员）的BDUSS？

**Comment by TkzcM** [comment]
> > 在 BDUSS 和 SVIPBDUSS 正确，且 clienttype 为 12 的情况下，获取到的链接 expires=8h
> > 所以检查你的cookie吧
> 
> 请问一下 BDUSS 和 SVIPBDUSS 有什么区别吗，能不能填写同一个百度账号（该账号已经是会员）的BDUSS？

BDUSS 普通用户或会员均可，SVIPBDUSS 必须为超级会员才可高速

**Comment by cloudtom** [comment]
> > > 在 BDUSS 和 SVIPBDUSS 正确，且 clienttype 为 12 的情况下，获取到的链接 expires=8h
> > > 所以检查你的cookie吧
> > 
> > 
> > 请问一下 BDUSS 和 SVIPBDUSS 有什么区别吗，能不能填写同一个百度账号（该账号已经是会员）的BDUSS？
> 
> BDUSS 普通用户或会员均可，SVIPBDUSS 必须为超级会员才可高速

的确是我之前在网上找的SVIPBDUSS有问题，现在试了好多个终于找到个能用的了，谢谢大佬解答我的问题！
