### ISSUE TITLE
离线aria下载

### ISSUE THREAD

**Issue by jiemo9527** [TkzcM/baiduwp#15]
推送离线connect failed，aria配置没有问题，可以使用其他功能插件推送aria。

**Comment by TkzcM** [comment]
使用http（不安全）访问即可

**Comment by jiemo9527** [comment]
还是不行

**Comment by TkzcM** [comment]
connect failed 后按 F12 把 console 里的 log 发一下

**Comment by jiemo9527** [comment]
log还是https上不能处理http请求，workers强制跳转https，怎么http访问。

**Comment by TkzcM** [comment]
绑定自己的域名，把 Always Use HTTPS 和 Automatic HTTPS Rewrites 关掉
或者给你的 aria2c 设置一个证书

**Comment by jiemo9527** [comment]
aria加证书当然可以不过不方便。workers通过cname到子域后，error523来源不可达，这边一般需要怎么处理

**Comment by jiemo9527** [comment]
已解决

**Comment by if1y** [comment]
推送过去的时候只会传递`链接`和`UA`，所以其实自己复制了再手动创建也差不多……
**能不能加上携带文件名？**

**Comment by TkzcM** [comment]
> 推送过去的时候只会传递`链接`和`UA`，所以其实自己复制了再手动创建也差不多……
> 还不用那么麻烦处理https的对称问题。
> 
> **能不能推送时再携带文件名？**
> 目前下载完成是一串id乱码，如果能辨识文件，推送的意义会大很多，也很方便。

可以，今天做

**Comment by if1y** [comment]
> > 推送过去的时候只会传递`链接`和`UA`，所以其实自己复制了再手动创建也差不多……
> > 还不用那么麻烦处理https的对称问题。
> > **能不能推送时再携带文件名？**
> > 目前下载完成是一串id乱码，如果能辨识文件，推送的意义会大很多，也很方便。
> 
> 可以，今天做

好的，辛苦啦

**Comment by TkzcM** [comment]
> 好的，辛苦啦

已完成
