### ISSUE TITLE
文件列表点击需要下载的文件后CF报错Error 1101

### ISSUE THREAD

**Issue by Hime77** [TkzcM/baiduwp#2]
已经将代码中的cookie替换，全部粘贴到CF Worker中部署上线后可以提取链接看到文件列表，但下一步就会报错。
提示如下：
![批注 2020-07-22 103843.png](https://ae01.alicdn.com/kf/Hdb8d991759524d3cb1477e08592b7b1bZ.png)

替换cookie的代码文件 ：https://wwe.lanzous.com/iu7nPeuv1fg
异常站点：[https://dl.frozen.workers.dev/](url)

**Comment by TkzcM** [comment]
![批注 2020-07-22 104914](https://user-images.githubusercontent.com/45264418/88128647-03475580-cc09-11ea-8d90-2ed5264c4bd2.jpg)

这种问题自己看一下log就能解决

**Comment by lyizhuo** [comment]
- 我使用的最新版js文件，遇到了同样的问题
- 已经替换好Cookie了
- bdwp.yitop.workers.dev

**Comment by Hime77** [comment]
> * 我使用的最新版js文件，遇到了同样的问题
> * 已经替换好Cookie了
> * bdwp.yitop.workers.dev

有人提交了pr，可以使用那个，配置起来相对方便一些。
