### ISSUE TITLE
删

### ISSUE THREAD

**Issue by siair** [TkzcM/baiduwp#21]
删

**Comment by TkzcM** [comment]
不需要 SVIP 的接口一个月前已在 Demo 使用过
不会公开

**Comment by Ecalose** [comment]
> 当前还有不需要Cookie(可能性较大)或者至少不需要svip的下载方法。k***donw 正在利用此漏洞，而非此项目的下载接口。从其返回的地址看，其没有使用svip账号，或者可能根本没有用Cookie，其vuk有些特别(有点类似 naifei.cc 后期使用的，很长)，毒限制连接数对其无效，速度快，没有封号的麻烦（从反应看本项目的接口依然会封号，如果确实是这样，猜测可能和下载量或者请求太多有关）。这似乎类似于 naifei.cc 后期使用的接口，毒可能没有全堵上。有兴趣的可下面回帖，一起讨论。

我很好奇

**Comment by Ecalose** [comment]
> 不需要 SVIP 的接口一个月前已在 Demo 使用过
> 不会公开

啊这

**Comment by siair** [comment]
> 不需要 SVIP 的接口一个月前已在 Demo 使用过
> 不会公开

现在还有效吗？速度如何？

**Comment by siair** [comment]
你是用什么抓的包？
