### ISSUE TITLE
能否为https://your.site/s/1qWsJVJ2添加自动填写提取码的功能

### ISSUE THREAD

**Issue by jiemo9527** [TkzcM/baiduwp#24]
能实现的话  使用更流畅

**Comment by TkzcM** [comment]
有 API
但是因为各种原因不打算实现
挺简单的，感兴趣可以自己弄一下

http://pwd.pandl.live/query?surl=1XKV7qKshaRO1EU_gCQqBrQ

**Comment by jiemo9527** [comment]
搞定
