### ISSUE TITLE
为什么有的 vuk 很长？

### ISSUE THREAD

**Issue by siair** [TkzcM/baiduwp#27]
https://bjbgp01.baidupcs.com/file/8553e92f1racc46bcaac9b03d370e3ef?
bkt=en-24c643f198a62f884c0864ed05833d8c92d4febc5b5f84afa91dbbc44d19739123139a0cd9dc7d00
&fid=3012946979-250528-197793286324740
&time=1602777917
&sign=FDTAXUGERLQlBHSKfWa-DCb740ccc5511e5e8fedcff06b081203-laa%2FkcTeJnQnkRd6kRxnkGm6xHI%3D
&to=75
&size=52428801
&sta_dx=52428801
&sta_cs=7
&sta_ft=txt
&sta_ct=5
&sta_mt=5
&fm2=MH%2CXian%2CAnywhere%2C%2Cdefault%2Cany
&ctime=1597423478
&mtime=1597423478
&resv0=-1
&resv1=0
&resv2=rlim
&resv3=2
&resv4=52428801
&vuk=9223372036854493472
&iv=0
&htype=
&randtype=
&origin=dlna
&newver=1
&newfm=1
&secfm=1
&flow_ver=3
&pkey=en-2c1b7312ed57422b1e088e57c4bebbcf31f56a2300343de5937cf7487998136fbc7579e4b5aeae76
&sl=78053454
&expires=8h
&rt=sh
&r=728855839
&sh=1
&vbdid=-
&fin=dis.zip
&rtype=1
&dp-logid=6702810786791564454
&dp-callid=0.1
&hps=1
&tsl=120
&csl=120
&fsl=-1
&csign=oTIEpvOWAUP7mChnjzI6kpHwkkU%3D
&so=0
&ut=6
&uter=0
&serv=0
&uc=1245499252
&ti=0887d9faa0e992642496738dddfc268f4c3291e5befa83f9305a5e1275657320
&hflag=30
&adg=n
&reqlabel=250528_f_41a34ea2f6aa5ca7ea80ee8b9d004705_-1_07a8945f7f02e4e3a09933cfa78586a4
&by=themis

像这个 &vuk=9223372036854493472 ，为何这么长？

**Comment by TkzcM** [comment]
不知道，去问百度

**Comment by siair** [comment]
你可能不知道，此下载地址和你的方法获取的不一样，此地址没有连接数限制，而且没用svip，且速度非常快，这里面有个参数非同寻常。
此下载地址用的虽是你的js，但参数修改了，与你的不一样
