### ISSUE TITLE
文件夹下载只能一个个链接的点击吗？

### ISSUE THREAD

**Issue by jzysl123** [TkzcM/baiduwp#3]
文件夹下的文件有啥快捷方法获取所有的链接吗 或者推送文件夹所有的链接到aria2 一个个点废脑

**Comment by TkzcM** [comment]
没有办法，下的太快会触发验证码

**Comment by wiosk** [comment]
> 没有办法，下的太快会触发验证码

可以考虑一下推送10个，不会触发验证码。
