### ISSUE TITLE
请问大佬cloudflare worker 在download页面报1101错误，是cf不支持了吗？还是需要设置什么吗

### ISSUE THREAD

**Issue by bestyy** [TkzcM/baiduwp#6]
请问大佬cloudflare worker 在download页面报1101错误，是cf不支持了吗？还是需要设置什么吗，感谢。
设置了BDUS和sToken

**Comment by bestyy** [comment]
已解决，原来是我少填了BDUS和STOKEN，感谢大佬的分享

**Comment by wsxftp** [comment]
我也遇到相同的问题 ，但是 BDUS 和STOKEN 都是有填写 的

**Comment by TkzcM** [comment]
> 我也遇到相同的问题 ，但是 BDUS 和STOKEN 都是有填写 的

去 quick edit 看 console 里的 log

**Comment by lyizhuo** [comment]
> 我也遇到相同的问题 ，但是 BDUS 和STOKEN 都是有填写 的

我也一样 检查过所有要填的位置了

**Comment by cloudtom** [comment]
console 里的 log显示：

Uncaught (in promise) TypeError: Cannot read property 'substring' of null
    at download (worker.js:635)
    at async handleRequest (worker.js:657)
download @ worker.js:635
Promise.catch (async)
(anonymous) @ worker.js:715
Uncaught (in response) TypeError: Cannot read property 'substring' of null

**Comment by lyizhuo** [comment]
> 有4个位置都需要修改BDUSS，不要漏了

可以说一下是哪几行需要修改吗，谢谢

**Comment by cloudtom** [comment]
> > 有4个位置都需要修改BDUSS，不要漏了
> 
> 可以说一下是哪几行需要修改吗，谢谢

用最新版的代码吧，代码更新了，新版代码只用改一个位置了

**Comment by lyizhuo** [comment]
> > > 有4个位置都需要修改BDUSS，不要漏了
> > 
> > 
> > 可以说一下是哪几行需要修改吗，谢谢
> 
> 用最新版的代码吧，代码更新了，新版代码只用改一个位置了

我今天用了最新的代码 也是出现1101错误

**Comment by cloudtom** [comment]
> > > > 有4个位置都需要修改BDUSS，不要漏了
> > > 
> > > 
> > > 可以说一下是哪几行需要修改吗，谢谢
> > 
> > 
> > 用最新版的代码吧，代码更新了，新版代码只用改一个位置了
> 
> 我今天用了最新的代码 也是出现1101错误

检查下BDUSS和stoken有没有填错，最后面不要有分号： ；
